### PR TITLE
1st PR of Python/GT4Py implementation (Geometry, GeometryConfig, & GT4PyConfig)

### PR DESCRIPTION
**Pull request by robgpita**
## Proposed changes

This is the first of ~5 PRs that will introduce a Python/GT4Py implementation of the Shallow Water code.

Add ShallowWaterGeometryConfig, ShallowWaterGT4PyConfig, & ShallowWaterGeometry classes complete with tests.

Add a `.yml` file in `test_input/` for testing purposes. Modify `.gitignore`.

## Types of changes

What types of changes does your code introduce?

- [ ] Bugfix (Change which fixes an issue)
- [x] New feature (Change which adds functionality)
- [x] Enhancement to existing functionality (non-breaking change which improves existing code or documentation)
- [ ] Breaking change (fix or feature that changes results and requires updates to test baselines)
- [ ] Documentation Update

## Checklist

_You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/NOAA-GSL/SENA-shallow-water/blob/develop/CONTRIBUTING.md) document
- [x] I have ensured all my changes contribute to a common purpose
- [x] I have verified my change does not add debug code
- [x] I have verified my change does not add code that is commented out
- [x] I have verified unit tests pass locally with my changes
- [x] I have verified my changes adhere to style guidelines
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if appropriate)

## Reviewers' checklist

The following is a checklist for reviewers to consider when reviewing this pull request.

#### Implementation

- [ ] Does this code do what it is supposed to do?
- [ ] Can the code be simplified?
- [ ] Does the code add unwanted compile-time or run-time dependencies?
- [ ] Is the code at the correct abstraction level?
- [ ] Is the code modular enough?
- [ ] Does similar functionality already exist in the codebase? If so, why wasn't it used?
- [ ] Can you think of a different solution that is substantially better in terms of code maintenance, readability, or performance?

#### Logic Errors and Bugs

- [ ] Can you think of a use case in which the code does not behave properly?
- [ ] Can you think of any inputs or external events that could break the code?

#### Error handling and logging

- [ ] Is error handling done correctly?
- [ ] Should any logging or debuggging be added or removed?
- [ ] Are error messages user friendly?

#### Usability

- [ ] Is the API intuitive to use?
- [ ] Is the API well documented?

#### Testing and testability

- [ ] Do the tests pass?
- [ ] Is the code testable?
- [ ] Do the tests reasonably cover the code change?
- [ ] Are there additional edge cases or inputs that should be tested?

#### Performance

- [ ] Do you think the code change will negatively impact performance?
- [ ] Do you see any potential to improve the performance of the code?

#### Dependencies

- [ ] Does this change require updates to documenation, configuration?  If so, what that done?
- [ ] Does this change affect backward compatibility?

#### Readability

- [ ] Is the code easy to understand?
- [ ] Can the readability be improved with smaller routines?
- [ ] Can the readability be improved with different subroutine/variable names?
- [ ] Is the data flow understandable?
- [ ] Could comments in the code be improved to add clarity?
- [ ] Is there any commented out code?
- [ ] Does the code conform to the style guide (Fortran style compliance cannot be checked automatically)

### CODE REVIEW

**Comment by christopherwharrop-noaa** [comment]
@robgonzalezpita - Looks like we need to update the MacOS GHA as it appears the unlink for gcc has changed.

**Comment by robgpita** [comment]
@christopherwharrop-noaa Now it seems as though `brew install netcdf` isn't installing netcdf fortran, or the `nf-config` command isn't working.

**Comment by christopherwharrop-noaa** [comment]
I saw that.  I was just trying to figure out why that was happening.  If we can't find a quick answer we may have to just turn off that test until we can sort it out.

**Review by christopherwharrop-noaa — DISMISSED** [review]
Looks good to me.

**Review by christopherwharrop-noaa — APPROVED** [review]

**Pull request merged**
