### PR TITLE
Add Github Actions workflow and remove shallow-water-demo remnants

### PR DESCRIPTION
**Pull request by christopherwharrop-noaa**
Add missing .github directory containing templates and GA workflows.  Revise README and CONTRIBUTING guide to remove references to shallow-water-demo.

### CODE REVIEW

**Comment by robgpita** [comment]
Looks good to me. Only thing I'd mention would be to add the `main` branch to the `pull_request` event in the github actions workflows. I'm assuming we'd only merge the develop branch into main (which will be tested), but I'd say that running the github actions workflows on a PR to the main branch should take place as well (this PR for example).

**Review by robgpita — DISMISSED** [review]

**Comment by christopherwharrop-noaa** [comment]
Good catch.  I missed that one.  I'll add `main` and then push again.

**Comment by christopherwharrop-noaa** [comment]
@robgonzalezpita - I had to make several fixes since some things from the old workflow were broken. When you get a chance, please give it another look.  All tests are passing now.

**Review by robgpita — APPROVED** [review]
Tests pass! Surprised OpenMPI took 3 hours to install.

**Pull request merged**
